apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-dev-317800
  artifacts:
    - image: us.gcr.io/ticketing-dev-317800/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
